apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-master

resources:
- targeting-service.yaml

images:
- name: targeting-service
  newName: 010533939486.dkr.ecr.us-east-1.amazonaws.com/togglemaster/targeting-service
  newTag: v0.0.0-bootstrap
