apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-master

resources:
- auth-service.yaml

images:
- name: auth-service
  newName: 965145516306.dkr.ecr.us-east-1.amazonaws.com/togglemaster/auth-service
  newTag: 62315726cd232e1ba60d5a66ef7650ceed0adb6d
