apiVersion: v1
kind: ConfigMap
metadata:
  name: toggle-master-config
  namespace: toggle-master
data:
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1
  AWS_DYNAMODB_TABLE: ToggleMasterAnalytics
  AUTH_SERVICE_URL: http://auth-service:8001
  FLAG_SERVICE_URL: http://flag-service:8002
  TARGETING_SERVICE_URL: http://targeting-service:8003
