apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-master

resources:
- platform
- apps/auth-service
- apps/flag-service
- apps/targeting-service
- apps/evaluation-service
- apps/analytics-service
