apiVersion: v1
kind: Secret
metadata:
  name: toggle-master-secrets
  namespace: toggle-master
type: Opaque
data:
  # Gere os valores com PowerShell:
  # [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("valor"))
  # Ou, em bash: echo -n 'valor' | base64
  AUTH_DATABASE_URL: cmVwbGFjZS1tZQ==
  FLAG_DATABASE_URL: cmVwbGFjZS1tZQ==
  TARGETING_DATABASE_URL: cmVwbGFjZS1tZQ==
  REDIS_URL: cmVwbGFjZS1tZQ==
  AWS_SQS_URL: cmVwbGFjZS1tZQ==
  MASTER_KEY: cmVwbGFjZS1tZQ==
  SERVICE_API_KEY: dG1fa2V5X2xvY2FsX2Rldg==
