apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: toggle-master
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 010533939486.dkr.ecr.us-east-1.amazonaws.com/analytics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          env:
            - name: PORT
              value: "8005"
            - name: AWS_SQS_URL
              valueFrom:
                secretKeyRef:
                  name: toggle-master-secrets
                  key: AWS_SQS_URL
            - name: AWS_DYNAMODB_TABLE
              valueFrom:
                configMapKeyRef:
                  name: toggle-master-config
                  key: AWS_DYNAMODB_TABLE
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: toggle-master-config
                  key: AWS_REGION
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: toggle-master-config
                  key: AWS_DEFAULT_REGION
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: toggle-master
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 8005
      targetPort: 8005

