apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-master

resources:
- analytics-service.yaml

images:
- name: analytics-service
  newName: 415764219943.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics-service
  newTag: v0.0.0-bootstrap
