apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-master

resources:
- analytics-service.yaml

images:
- name: analytics-service
  newName: 965145516306.dkr.ecr.us-east-1.amazonaws.com/togglemaster/analytics-service
  newTag: 4211c44ff854f96dcb62434b65fa795678e56c7d
