apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service-sqs
  namespace: toggle-master
spec:
  scaleTargetRef:
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURLFromEnv: AWS_SQS_URL
        awsRegion: us-east-1
        queueLength: "10"
        identityOwner: operator
