apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: toggle-master-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/FIAP-Teach-Challenge-2/toggle-master-infra.git
    targetRevision: main
    path: aws/platform
  destination:
    server: https://kubernetes.default.svc
    namespace: toggle-master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
