apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toggle-master

resources:
- evaluation-service.yaml

images:
- name: evaluation-service
  newName: 965145516306.dkr.ecr.us-east-1.amazonaws.com/togglemaster/evaluation-service
  newTag: 6f555cae5ba43a8fde509a4f35032fe9116cdd03
